skillMetadata:
  sections:
  - name: Login
    fields:
    - name: user_name
      type: text
      label: username
      value: ''
    - name: password
      type: password
      label: Confluence password
      value: ''
    - name: confluence_url
      type: text
      label: Confluence URL
      value: ''
    - name: telegram_bot_key
      type: password
      label: Telegram Bot Key
      value: ''
    - name: telegram_chat_id
      type: text
      label: Telegram Group Chat ID
      value: ''
